/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.tjayr.model;


import org.infinispan.protostream.annotations.ProtoField;

public class Module  {

  private String code;
  private String title;
  private String academicYear;
  private Integer courseReference;

  public Module() {}

  @ProtoField(1)
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  @ProtoField(2)
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  @ProtoField(3)
  public String getAcademicYear() {
    return academicYear;
  }

  public void setAcademicYear(String academicYear) {
    this.academicYear = academicYear;
  }

  @ProtoField(4)
  public Integer getCourseReference() {
    return courseReference;
  }

  public void setCourseReference(Integer courseReference) {
    this.courseReference = courseReference;
  }
}
